server:
  port: 8080

spring:
  application:
    name: duckest
  datasource:
    url: jdbc:postgresql://localhost:11111/duckest
    username: default
    password: default
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/master.xml