version: '3'
services:
  postgres:
    image: library/postgres:9.6.8
    ports:
      - "11111:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=default
      - POSTGRES_USER=default
      - POSTGRES_DB=duckest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
